sudo: false
language: ruby
script: bin/rspec
rvm:
  - 2.6.6
gemfile:
  - spec/gemfiles/Gemfile.rails-5.2.x
  - spec/gemfiles/Gemfile.rails-6.0.x
matrix:
  exclude:
    - rvm: 2.6.6
      gemfile: spec/gemfiles/rails-5.2.x.gemfile
    - rvm: 2.6.6
      gemfile: spec/gemfiles/rails-6.0.x.gemfile
  fast_finish: true
notifications:
  email: false
